### ISSUE TITLE
Colon delimitation

### ISSUE THREAD

**Issue by felixcollins** [psryland/rylogic_code#1]
Hey man it is ironic that the pattern configuration uses JSON bu there is no : delimiter set up by default! Awesome plugin by the way. I gave it a plug on the vscode marketplace. I can't believe it has only 43 downloads so far.
```        {
            "name": "Colon delimiter",
            "leading_space": 0,
            "patterns": [
                {
                    "pattern": ":",
                    "offset": 0,
                    "minimum_width": 1,
                    "comment": "Colon characters"
                }
            ]
        },
```

**Comment by psryland** [comment]
Cheers!

So, adding that extra pattern highlighted a bug related to changing settings. The old patterns weren't being flushed each time the settings changed! I've fixed that bug and added the colon delimiter pattern to the default settings.  Version 1.10.5 has the fixes.
